### ISSUE TITLE
Use argparse for argv parsing

### ISSUE THREAD

**Issue by doowzs** [Michael1015198808/zsh-vocab#1]
**<TL; DR>**

Use `import argparse` to parse arguments instead of the manual method.

**Why**

`argparse` can provider better helper of how to use this program and let developers control arguments better.

**Comment by Michael1015198808** [comment]
Excellent idea! I've to be sorry for my C-style Python code. I'll fix what you say in the next release.

**Comment by Michael1015198808** [comment]
Thaks for waiting!
We've imported argparse into our project, which is on branch dev.
